[version]
number = 555

[updates]
enabled = true

[[nodes]]
name = "redis-1.dbright.io"
stop = ''''''
reboot = true

[[nodes]]
name = "redis-2.dbright.io"
stop = '''sleep 20; echo "hello, I'm `hostname`"'''

[[nodes]]
name = "redis-3.dbright.io"

[[nodes]]
name = "redis-4.dbright.io"

[[nodes]]
name = "redis-5.dbright.io"

[[nodes]]
name = "redis-6.dbright.io"

[commoncmds]
stopcmd = '''sleep 10'''
startcmd = '''echo "I'm using the common start..."'''
validatecmd = '''echo "\`hostname\` started"'''
reboot = false
skip = false
