#!/usr/bin/sh

function config_apply () {
    sudo rm -rf /opt/update-tracking/REBOOTED
    version_number=`grep number /opt/update-tracking/config.toml | cut -d "=" -f2`
    sudo hab config apply {{svc.service}}.{{svc.group}} $version_number /opt/update-tracking/config.toml
    sleep 10
}
function run_start () {
    sudo bash {{pkg.svc_config_path}}/{{sys.hostname}}_start
}
function run_validate () {
    sudo bash {{pkg.svc_config_path}}/{{sys.hostname}}_validate
}
function make_cmd_files () {
    # Populate the cmd files with defaults if no config has been applied to the cluster yet.
    if [ ! -f "{{../pkg.svc_config_path}}/{{../sys.hostname}}_start" ]; then
        echo "{{../pkg.svc_config_path}}/{{../sys.hostname}}_start, does not exist, creating default"
        touch {{../pkg.svc_config_path}}/{{../sys.hostname}}_start
        echo "echo \"[{{../sys.hostname}}] Default start command.\"" > {{../pkg.svc_config_path}}/{{../sys.hostname}}_start
    fi
    if [ ! -f "{{../pkg.svc_config_path}}/{{../sys.hostname}}_stop" ]; then
        echo "{{../pkg.svc_config_path}}/{{../sys.hostname}}_stop, does not exist, creating default"
        touch {{../pkg.svc_config_path}}/{{../sys.hostname}}_stop
        echo "echo \"[{{../sys.hostname}}] Default stop command.\"" > {{../pkg.svc_config_path}}/{{../sys.hostname}}_stop
    fi
    if [ ! -f "{{../pkg.svc_config_path}}/{{../sys.hostname}}_validate" ]; then
        echo "{{../pkg.svc_config_path}}/{{../sys.hostname}}_validate, does not exist, creating default"
        touch {{../pkg.svc_config_path}}/{{../sys.hostname}}_validate
        echo "echo \"[{{../sys.hostname}}] Default validate command.\"" > {{../pkg.svc_config_path}}/{{../sys.hostname}}_validate
    fi
}

run=true

function run_app () {
    make_cmd_files
    run_start
    while run_validate; do
        sleep 10
        run_validate
    done
}

if [ -f "/opt/update-tracking/REBOOTED" ]; then
    counter=30
    while [ $counter -gt 0 ]; do
        echo "[RUN] Applying config in $counter seconds..."
        sleep 1
        counter=$(( $counter - 1 ))
    done
    config_apply
fi

run_app
